/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppSeoRouteImport } from './routes/_app.seo'
import { Route as AppReportingRouteImport } from './routes/_app.reporting'
import { Route as AppCrmRouteImport } from './routes/_app.crm'
import { Route as AppContentRouteImport } from './routes/_app.content'
import { Route as AppCampaignsRouteImport } from './routes/_app.campaigns'
import { Route as AppBrandsRouteImport } from './routes/_app.brands'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSeoRoute = AppSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => AppRoute,
} as any)
const AppReportingRoute = AppReportingRouteImport.update({
  id: '/reporting',
  path: '/reporting',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmRoute = AppCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AppRoute,
} as any)
const AppContentRoute = AppContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AppRoute,
} as any)
const AppCampaignsRoute = AppCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AppRoute,
} as any)
const AppBrandsRoute = AppBrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/brands': typeof AppBrandsRoute
  '/campaigns': typeof AppCampaignsRoute
  '/content': typeof AppContentRoute
  '/crm': typeof AppCrmRoute
  '/reporting': typeof AppReportingRoute
  '/seo': typeof AppSeoRoute
  '/settings': typeof AppSettingsRoute
}
export interface FileRoutesByTo {
  '/brands': typeof AppBrandsRoute
  '/campaigns': typeof AppCampaignsRoute
  '/content': typeof AppContentRoute
  '/crm': typeof AppCrmRoute
  '/reporting': typeof AppReportingRoute
  '/seo': typeof AppSeoRoute
  '/settings': typeof AppSettingsRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/brands': typeof AppBrandsRoute
  '/_app/campaigns': typeof AppCampaignsRoute
  '/_app/content': typeof AppContentRoute
  '/_app/crm': typeof AppCrmRoute
  '/_app/reporting': typeof AppReportingRoute
  '/_app/seo': typeof AppSeoRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/brands'
    | '/campaigns'
    | '/content'
    | '/crm'
    | '/reporting'
    | '/seo'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/brands'
    | '/campaigns'
    | '/content'
    | '/crm'
    | '/reporting'
    | '/seo'
    | '/settings'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/_app/brands'
    | '/_app/campaigns'
    | '/_app/content'
    | '/_app/crm'
    | '/_app/reporting'
    | '/_app/seo'
    | '/_app/settings'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/seo': {
      id: '/_app/seo'
      path: '/seo'
      fullPath: '/seo'
      preLoaderRoute: typeof AppSeoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reporting': {
      id: '/_app/reporting'
      path: '/reporting'
      fullPath: '/reporting'
      preLoaderRoute: typeof AppReportingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/crm': {
      id: '/_app/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AppCrmRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/content': {
      id: '/_app/content'
      path: '/content'
      fullPath: '/content'
      preLoaderRoute: typeof AppContentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/campaigns': {
      id: '/_app/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof AppCampaignsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/brands': {
      id: '/_app/brands'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof AppBrandsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBrandsRoute: typeof AppBrandsRoute
  AppCampaignsRoute: typeof AppCampaignsRoute
  AppContentRoute: typeof AppContentRoute
  AppCrmRoute: typeof AppCrmRoute
  AppReportingRoute: typeof AppReportingRoute
  AppSeoRoute: typeof AppSeoRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBrandsRoute: AppBrandsRoute,
  AppCampaignsRoute: AppCampaignsRoute,
  AppContentRoute: AppContentRoute,
  AppCrmRoute: AppCrmRoute,
  AppReportingRoute: AppReportingRoute,
  AppSeoRoute: AppSeoRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
